# Generated by Django 3.1.1 on 2020-10-19 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.SmallIntegerField(choices=[(0, '运营类'), (1, '技术类'), (2, '设计类')], verbose_name='职位类型')),
                ('job_name', models.TextField(max_length=200)),
                ('job_city', models.SmallIntegerField(choices=[(0, '北京'), (1, '上海'), (2, '广州')], verbose_name='地点')),
                ('job_responsibility', models.TextField(max_length=1024, verbose_name='职位描述')),
                ('job_requirements', models.TextField(max_length=1024, verbose_name='职位要求')),
                ('created_at', models.DateTimeField(verbose_name='创建时间')),
                ('modified_at', models.DateTimeField(verbose_name='修改时间')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
        ),
    ]
